test:
    cargo test

build:
    cargo build

# runs the specified bench
bench target:
    cargo bench --bench "{{target}}" --features "bench"

install:
    cargo install -f just

add-bench:
    cargo criterion --bench wasmtime --message-format=json | criterion-table > BENCHMARKS.md