test:
    cargo test --features "env_logger"

build:
    cargo build

# runs the specified bench
bench target:
    RUST_BACKTRACE=1 cargo bench --bench "{{target}}" --features "bench"

install:
    cargo install -f just

add-bench:
    RUST_BACKTRACE=1 cargo criterion --bench wasmtime --features "bench" --message-format=json | criterion-table > BENCHMARKS.md