[tasks.build]
clear = true
dependencies = [
    "cargo-build",
    "llvm-strip",
    "wasm-opt",
    "wasm2wat"
]

[tasks.cargo-build]
env = { "RUSTFLAGS" = "-C target-feature=+multivalue"}
script = "cargo +nightly build --target=wasm32-unknown-unknown --release -Z build-std=core"

[tasks.pwd]
command = "pwd"

[tasks.llvm-strip]
command = "llvm-strip"
args = [
    "--keep-section=name", 
    "../../target/wasm32-unknown-unknown/release/wasm_stdlib.wasm"
    ]

[tasks.wasm-opt]
command = "wasm-opt"
args = [
    "-O3", 
    "-o", "../../target/wasm32-unknown-unknown/release/wasm_stdlib.wasm", 
    "../../target/wasm32-unknown-unknown/release/wasm_stdlib.wasm"]

[tasks.wasm2wat]
command = "wasm2wat"
args = [
    "../../target/wasm32-unknown-unknown/release/wasm_stdlib.wasm",
    "-f",
    "-o", "../../target/wasm32-unknown-unknown/release/wasm_stdlib.wat"
]